# Net Interest Margin (NIM)
# -------------------------
# Overview:
# NIM measures the difference between the interest income generated by banks or other 
# financial institutions and the amount of interest paid out to their lenders, relative 
# to the amount of their assets. It represents the profit margin of the lending activity.
#
# Desired Value:
# A higher NIM indicates a more profitable financial institution, as it's earning more 
# from its assets than it's paying out in interest. However, extremely high NIM values 
# may signal higher lending risks, so it's essential to balance profitability with safe lending practices.

def calculate_nim(interest_income, interest_paid, total_assets):
    """Calculate the Net Interest Margin (NIM)."""
    return (interest_income - interest_paid) / total_assets

# Hard-coded values (These are just sample values and should be replaced with real-world data)
sample_interest_income = 15.0  # Interest income of $15,000,000, represented as 15.0
sample_interest_paid = 10.0    # Interest paid of $10,000,000, represented as 10.0
sample_total_assets = 200.0    # Total assets of $200,000,000, represented as 200.0

# Calculating NIM from the sample values
sample_nim = calculate_nim(sample_interest_income, sample_interest_paid, sample_total_assets)

print(f"Interest Income is: ${sample_interest_income:.2f} million")
print(f"Interest Paid is: ${sample_interest_paid:.2f} million")
print(f"Net Interest Margin (NIM) is: {sample_nim*100:.2f}%")
